### ISSUE TITLE
When I try to run the example jupyternotebook file, a ‘Keyerror" arose

### ISSUE THREAD

**Issue by Florianismeandonlyme** [gusamarante/dsgepy#4]
![image](https://user-images.githubusercontent.com/58820847/197464448-7a59fe02-7e66-4c08-9189-fb3401ed3d04.png)

**Comment by gusamarante** [comment]
Hello Florian,
Unfortunately I cannot help you with just this information. What I can say
is that I am working on more detailed examples to be published soon.
Hopefully they will be able to better help you understand how the library
works. I would like to remind you that the library is still in very early
stages of development and any help (through pull requests) is highly
appreciated. So if you run into bugs, major design problems and/or
suggestions, please open a pull request.

Best,
Gustavo Amarante

**Comment by mhidper** [comment]
Thank you for this job, Gustavo.
I have a problem.
When running Jupyter, I encounter an issue with the creation of the H5. You mention that if it doesn't exist, it's created. However, when I estimate the DSGE, it indicates that it doesn't exist and gives an error. Thank you."

**Comment by gusamarante** [comment]
Hello there. I am glad that you want to use DSGEPy.
With the information you sent me, it is not possible to pin down any
problems. But I will suggest a workaround for the most common cause of
issues. Are you using the correct version of pykalman? On the dsgepy
README, it points you to the correct version of the library that you need
to use. But here is the link <https://github.com/gusamarante/pykalman> to
it. Make sure that when you set up your python environment with this
version of pykalman.

Best,
Gustavo Amarante

**Comment by mhidper** [comment]
Hi, Gustavo!! thanks for the response. 
I believe so, but I'm not entirely sure. I'll make sure that it's the version I'm using and I'll let you know.

**Comment by mhidper** [comment]
Hello, 
The problem seems to be related with the file hd5 in pytables. 
I have this error:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
File [c:\Users\Usuario\anaconda3\envs\tf\lib\site-packages\dsgepy\lineardsge.py:171](file:///C:/Users/Usuario/anaconda3/envs/tf/lib/site-packages/dsgepy/lineardsge.py:171), in DSGE.estimate(self, file_path, nsim, ck, save_interval)
    [170](file:///C:/Users/Usuario/anaconda3/envs/tf/lib/site-packages/dsgepy/lineardsge.py:170) try:
--> [171](file:///C:/Users/Usuario/anaconda3/envs/tf/lib/site-packages/dsgepy/lineardsge.py:171)     df_chains = pd.read_hdf(file_path, key='chains')
    [172](file:///C:/Users/Usuario/anaconda3/envs/tf/lib/site-packages/dsgepy/lineardsge.py:172)     sigmak = pd.read_hdf(file_path, key='sigmak')

File [c:\Users\Usuario\anaconda3\envs\tf\lib\site-packages\pandas\io\pytables.py:418](file:///C:/Users/Usuario/anaconda3/envs/tf/lib/site-packages/pandas/io/pytables.py:418), in read_hdf(path_or_buf, key, mode, errors, where, start, stop, columns, iterator, chunksize, **kwargs)
    [417](file:///C:/Users/Usuario/anaconda3/envs/tf/lib/site-packages/pandas/io/pytables.py:417) if not exists:
--> [418](file:///C:/Users/Usuario/anaconda3/envs/tf/lib/site-packages/pandas/io/pytables.py:418)     raise FileNotFoundError(f"File {path_or_buf} does not exist")
    [420](file:///C:/Users/Usuario/anaconda3/envs/tf/lib/site-packages/pandas/io/pytables.py:420) store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)

FileNotFoundError: File ejemplo.h5 does not exist

Thanks
